name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Only trigger the workflow for the main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: (Optional) Any other build or preparation steps can be added here
      # If you have any additional setup, you can add it here

  deploy_and_test:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      # Step 1: Checkout code again for the deployment job
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # GitHub Secret for Vercel Token
        run: npx vercel --prod --token ${{ env.VERCEL_TOKEN }}

      # Step 3: Wait for the deployment to finish
      # Optional, to allow time for the deployment to complete
      - name: Wait for Deployment
        run: sleep 30  # Wait for 30 seconds to ensure deployment is live

      # Step 4: Test the API using curl
      - name: Test the API endpoint
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://mlops-assignment-1-ten.vercel.app//api/predict)
          if [ "$response" -ne 200 ]; then
            echo "API test failed with status code: $response"
            exit 1
          else:
            echo "API test passed with status code: $response"
