name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install flake8 pylint

      - name: Lint code
        run: |
          flake8 --ignore=E501 .
          pylint app.py main.py test.py

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest test.py

  build:
    runs-on: ubuntu-latest
    needs: [linting, testing]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build Docker image
        run: |
          docker build -t house-price-app:${{ github.sha }} .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel (Development)
        if: github.ref == 'refs/heads/dev'
        run: |
          vercel --prod

      - name: Deploy to Vercel (Staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          vercel --prod

      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          vercel --prod
